### ISSUE TITLE
Unable to create texture from rendered text: Couldn't find glyph

### ISSUE THREAD

**Issue by walkero-gr** [Oliveshark/breakhack#64]
**Describe the bug**
I am working on a BreakHack port for AmigaOS 4. Although that the game works pretty well, with a few problems here and there, I have an issue with some texts not shown, like showing the how_to_play_tooltip, like it is shown at the following screenshot.

![BreakHack 4 0 3 _001_20220831](https://user-images.githubusercontent.com/14014909/187685588-e0928767-628e-4851-8db5-bc13040e0fbb.png)

By investigating it seems that the error comes from the line [182](https://github.com/Oliveshark/breakhack/blob/dev/src/texture.c#L182) when an outlined font is requested. I altered the code to avoid using outline fonts and the texts appear just fine, except that they are really thick because white texts and white outline mix.

**To Reproduce**
I am not sure how you can reproduce it since this operating system is commercial and runs only on specific PPC-based hardware.

**Expected behavior**
The expected behaviour is to show those texts fine

**Screenshots**
Other screens seem to work fine like:

![BreakHack 4 0 3 _001_20220830](https://user-images.githubusercontent.com/14014909/187687403-39c0a1bb-47b3-4260-b921-045138c06a72.png)

![BreakHack 4 0 3 _002_20220830](https://user-images.githubusercontent.com/14014909/187687439-1febb378-a53c-4888-8ee5-04df379fa598.png)

**Desktop (please complete the following information):**
Latest code from repo is used for the port
SDL 2 v2.0.20
SDL2_ttf  v2.20.1

**Additional context**
My questions for now:
1. Is the repo code the latest available that I need for the port?
2. Is the game still in development and make sense for me to work on fixes? Would you accept PRs with those fixes?
3. Do you have any info to share on how to tackle that issue?

And last, but not least, I bought this awesome game on steam, and I compared the .pack files for data and assets, with the ones that exist in this repo. Should there be any changes? The .pack files seem like plain zip files, right? Is there a reason why you choose to use physfs library and do not have those files extracted in the first place? I am asking because physfs is one more dependency for your code that could be avoided, but I might be wrong on that, since I haven't investigated the code completely, and I might miss something.

Thank you so much for your help.

**Comment by walkero-gr** [comment]
So, I investigated the issue more today and I came up with a simple solution that seems to work fine.
What I did was to change the [TTF_RenderText_Solid()](https://github.com/Oliveshark/breakhack/blob/dev/src/texture.c#L168) with TTF_RenderText_Blended(). It seems the problem is on the returned values where TTF_RenderText_Blended() returns a high quality ARGB surface, but the TTF_RenderText_Solid() returns an 8-bit surface, and possibly that's the reason it fails.

I would like to ask you why you use TTF_RenderText_Solid() in first place? Would my solution be a valid one or there are issues you tried to fix?

Some screenshots:
![BreakHack 4 0 3 _001_20220831](https://user-images.githubusercontent.com/14014909/187775799-915419a7-1059-4ce4-823f-14f41de07ae8.png)

![BreakHack 4 0 3 _002_20220831](https://user-images.githubusercontent.com/14014909/187775828-c650fa26-8c25-4fb7-8cd4-9199585fb84e.png)

**Comment by LiquidityC** [comment]
Hello and thanks for a very extensive and explanatory report. Super cool that you are porting to Amiga. Makes me wish I had one.

As for your questions:
- **Why use `TTF_RenderText_Solid()`?** I have no idea. Probably just legacy from when I introduced outlined text. All the surrounding logic seems to have been added in the same commit. If you send a PR I will gladly merge it.
- **Is the repo the latest code?** Yes. With the omission of the steam api there is no difference.
- **Is the game still in development?** It's being maintained but I'm not extending the gameplay so to speak. The game is complete and I'll maintain the code to make sure it builds and runs. I will gladly accept PRs with fixes.
- **Why physfs?** A few reasons. The first is just general comfort. Shipping zip files with everything that the game needs in one compressed file saves space and is easier to manage (should one want to move the files for some obscure reason). It obscures the lua files from users. It sandboxes the lua scripts and file io into a given directory (this was the big reason).

**Comment by walkero-gr** [comment]
@LiquidityC Thank you so much for your reply and for answering my questions.
So far the game works pretty well on my system, but I have to fix a couple of issues in the fullscreen mode. It seems that the graphics are not scaled as they should. But more on that in future issue reports if needed.

When I finish it and if I am happy with the result, I will probably make a PR.

Thank you again.
